### ISSUE TITLE
5.3, a way with function_exists

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Autoload#14]
There is a method

```
protected function isDeclared($spec)
{
    return class_exists($spec, false)
        || interface_exists($spec, false)
        || trait_exists($spec, false);
}
```

probably we can use `function_exists` call for traits before calling it 

http://php.net/manual/en/function.function-exists.php

**Comment by pmjones** [comment]
I don't understand -- why would we need a function_exists() call here?

**Comment by harikt** [comment]
I was thinking of 5.3 compatibility. If a call for trait_exists will end up in error for this is 5.4 + . So if any only if the function exists we look for it .

**Comment by pmjones** [comment]
Gotcha.  Are we still thinking that backporting to PHP 5.3 is something we want to spend time on?

**Comment by harikt** [comment]
nope. But for autoloading isn't that good ?

**Comment by pmjones** [comment]
Well, if we intend the autoloader for php 5.4, and trait_exists() is always there for php 5.4, we don't need to check function_exists('trait_exists').

**Comment by harikt** [comment]
ok. Let us leave it for 5.4 then :) .
