### ISSUE TITLE
Note about v1 and v2 in README.md

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Autoload#16]
@pmjones I am seeing another issue with the v1 and v2 repos. Most of the people may not know we have 2 versions. Consider someone coming to README.md of develop-2 branch of aura/autoload . They read 

> Provides a PSR-4 (and limited PSR-0) autoloading facility

which is a bad thing I guess. For we already have good support in v1 .

I am thinking whether it is good to keep the branch information also in README.md mentioning develop is v1 , develop-2 is v2 .

What are your thoughts on this ?

**Comment by pmjones** [comment]
I'm OK with adding a note in the develop-2 README in the top-level description that points to v1 as full PSR-0 alternative, if you thinks it's needed. But as for keeping branch information in each README in all of Aura, I think that's probably overkill.

**Comment by harikt** [comment]
@pmjones I am talking only for Autoload. For when you are using psr-4 it should be noted to people that the olde PEAR style autoloaders will fail. Let them don't try it to understand ;) .

And I am happy with this in the README as you committed.
