### ISSUE TITLE
no underscores allowed?

### ISSUE THREAD

**Issue by jmcbee** [auraphp/Aura.Autoload#18]
May I ask what does that mean? I'm attempting to use Aura.Autoload with the dropbox sdk which uses PSR-0. Unfortunately, they use underscores.

https://github.com/dropbox/dropbox-sdk-php/blob/master/lib/Dropbox/Exception/InvalidAccessToken.php

Can I still use this?

Thanks.

**Comment by harikt** [comment]
use v1 of Aura.Autoload , v2 is psr-4 complaint. 

Hope that helps. If so may be you could close the issue.

Thank you.

**Comment by harikt** [comment]
I meant to press comment. Sorry :( . ( v1 is 1.x branch )

**Comment by jmcbee** [comment]
Hello,

What if I want to use both PSR-0 and PSR-4 libraries?

Thanks.

**Comment by harikt** [comment]
That seems you want to register two autoloaders psr0 and psr4. I feel in that case you should rely on composer.

**Comment by jmcbee** [comment]
I see. Thanks!
