### ISSUE TITLE
How to autoload self directory

### ISSUE THREAD

**Issue by drnkwati** [auraphp/Aura.Autoload#19]
How can we autoload several name spaces in current folder
Example
$loader->addPrefix('./', __DIR__ . '/');
Is it even possible like it's done in composer?
Thanks

**Comment by harikt** [comment]
@drnkwati yes it is possible.

use 1.x version : https://github.com/auraphp/Aura.Autoload/tree/1.0.2 . Docs have some examples. Hope that makes sense.

**Comment by drnkwati** [comment]
Sorry my question was never answered not even by the documentation.
What i mean is loading a directory to the global namespace. For example see the image below.
Check the loading of packages line. 
I can do this with composer and it works great. Can it also be done in aura loader. If it can't for then consider it a pull request. Thanks
![img_20170610_152022](https://user-images.githubusercontent.com/7881511/27003531-6c8cefe0-4df0-11e7-9233-88a6d2efd41f.jpg)

**Comment by harikt** [comment]
I believe what you are looking is without registering a path or namespace, it can load from packages folder. If so no. Why not use composer itself if that works great! ?

**Comment by drnkwati** [comment]
Thanks for responding.
Composer is great but for small projects i usually like simple tools and avoid the command line.
I really love this autoloader, and will be more excited if that functionality was added 
Thanks again

**Comment by drnkwati** [comment]
Composer generates a Composer\Autoload\ClassLoader that can be used stand alone.
