### ISSUE TITLE
file_exists and is_readable

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Autoload#3]
I guess  `is_readable()`  is a better choice than `file_exists()` for some have no read permission . Will it makes slow or can we add a require_one in try catch and throw the appropriate exception ? Like FileNotReadable something ?

**Comment by pmjones** [comment]
Changed, committed, and pushed.

**Comment by harikt** [comment]
Thank you for the fix . Commit over  https://github.com/auraphp/Aura.Autoload/commit/fc94c1a0f7eaddd9bd78bf67f4440fd0a9ada3b8
