### ISSUE TITLE
RFC splclassloader

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Autoload#4]
Hi @pmjones , 

Accoding to RFC at php.net , https://wiki.php.net/rfc/splclassloader the method is add , for the naming consistency is that ok that method name is add() than anything ?

public function add($resourceName, $resourcePath = null);

Is that ok that we also make add , than addPrefix , addPrefixes etc ?

**Comment by pmjones** [comment]
Yes, I'm good with that.  We should incorporate the constants, too, so that we can switch to it right away.

**Comment by pmjones** [comment]
I've made the changes. Not going to push until I have replaced the $loader->addPrefix() calls in all the other packages. Tomorrow.

**Comment by pmjones** [comment]
Changed, committed, and pushed.

**Comment by harikt** [comment]
Great . Thanks.
